### ISSUE TITLE
Hier können technische Fragen gestellt werden, die für alle Teilnehmer relevant sind.

### ISSUE THREAD

**Issue by pfrost** [TUBSAPISS2017/public#1]
@PaulFrost Eine Zuweisung ist möglich.

**Comment by TanerAp** [comment]
@PaulFrost 
Hallo, ich habe eine Frage zum Testing:
ich habe test.h und testDefinitionen.h entsprechend den Vorlagen erstellt. Und auch entsprechend modifiziert. Ich habe jedoch nicht verstanden, wie das ganze am Ende abläuft. 
Muss ich nun meinen fertigen Code einer Anforderung benutzen und in diesem Code die Funktionen aus testDefinitionen.h einzeln aufrufen? Oder ruft sich das am Ende automatisch im Code ab, weil oben RUNTEST steht? Woher soll der Code in diesem Fall wissen, wann was verglichen werden soll? Ich habe die Logik dahinter noch nicht verstanden.

**Comment by PaulFrost** [comment]
Moin, 
`RUNTEST` führt an der Stelle, wo es im Quelltext platziert ist, alle Testmethoden aus. Wenn zum Beispiel `RUNTEST` in der setup() Methode eingetragen ist, werden die Tests beim Setup des Arduinos durchgeführt. D.h. ihr könnt `RUNTEST` an einer beliebigen Stelle eures Programms hinzufügen.

Damit es klappt, muss

- `#define TEST` vor `#include "testDefinitionen.h"` stehen. Ohne `#define TEST` werden die Tests erst gar nicht hinzugefügt.
- und die von euch definierten Testfunktionen in `runTests()`aufgerufen werden

**Comment by TanerAp** [comment]
@PaulFrost 
Vielen Dank für die Antwort! 
Ich habe noch 2 Fragen, die sich nun ergeben haben:
1) Wie übergebe ich meiner Testmethode in testDefinitionen.h die nötigen Parameter aus dem Quelltext? Der Aufruf findet ja nur über "RUNTEST" statt. 
2) Ich möchte den Test zur Laufzeit des Codes auf einem Prototypen durchführen. In diesem Beispiel, ob eine LED auf HIGH bzw. auf LOW steht, wenn die entsprechenden Bedingungen/Eingaben gegeben sind. Ist das die richtige Herangehensweise?

**Comment by PaulFrost** [comment]
Frage 1: 
Das ist bei dieser Funktion nicht vorgesehen. Die benötigten Parameter sollten in der erstellten Testfunktion angelegt und den zu testenden Funktionen/Klassen übergeben werden. An dem zu testenden Quelltext soll so wenig wie möglich verändert werden. (Das ist auch der Grund für das RUNTEST Makro)

Frage 2: 
Du müsstest den Status der LEDs abfragbar gestalten. Ansonsten ist der Ansatz in Ordnung.
