### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by MarcusGr** [TUBSAPISS2017/public#4]
@PaulFrost : Inwieweit müssen die persönlich gesetzten Meilensteine dokumentiert werden?

Reicht eine Erwähnung im Zeitplan (mit Namen)?
Oder soll dies (wenn ja, wo) im Wiki dokumentiert (inkl. Erfolg oder nicht, Verschiebung etc) werden?

**Comment by PaulFrost** [comment]
Es wäre super, wenn die Meilensteine in der Dokumentation des Zeitplans erwähnt werden würden. Zum Beispiel: Wurde dieser Meileinstein erreicht oder warum konnte dieser nicht eingehalten werden?

Falls dieser Kommentar die Frage beantwortet, wäre es gut, wenn du dieses Issue schließen könntest.
