### ISSUE TITLE
Bilder in PDF?

### ISSUE THREAD

**Issue by TanerAp** [TUBSAPISS2017/public#6]
@PaulFrost 
Hallo Herr Frost, 
wie ich von einem Team-Mitglied erfahren habe, müssen wir JPEG-Dateien (wie z.B. Use-Case-Diagramme etc.) nicht nochmal extra als PDF hochladen. 
Gilt dies auch für PNG-Dateien? Können wir diese so im Wiki lassen?

**Comment by PaulFrost** [comment]
png-Dateien müssen nicht umgewandelt werden.

**Comment by TanerAp** [comment]
danke!
